### ISSUE TITLE
Registry Stability

### ISSUE THREAD

**Issue by dret** [w3c/tt-profile-registry#17]
it seems that the current policy does not make any assertions about the stability of identifiers and their meaning. this means that it is possible that identifiers get redefined by registry updates. many registries avoid this kind of semantics shift by disallowing updated, or only allowing updates that deprecate values. the reason is that typically, registry contents will be used to write code and and then any changes to entry semantics will break this code by redefining the meaning of an existing value.
https://tools.ietf.org/html/draft-wilde-registries-01#section-3.5 makes the point that it is a common pattern to disallow updating semantics. if that isn't done, i would recommend to add a note to developers that identifier semantics may change, which probably will break implementations, even though there is little they can actually do about it.

**Comment by mikedo** [comment]
the WG provides oversight/approval to the registry changes. so, some sanity will prevail over re-using code points and similar fatal issues. as you suggest, perhaps a good practice would be never to delete a profile - at worst, deprecate it, but even that would be exceptional. I'd support forbidding the "delete" operation.

for updates (version management) we should recommend the assignments be stable. and the WG can do that for its own profiles. but I'm not sure the WG can dictate how 3rd parties manage the evolution of their controlling specs except via recommendations.

can you propose specific edits?

**Comment by dret** [comment]
On 2016-05-10 12:14, Michael A Dolan wrote:

> the WG provides oversight/approval to the registry changes. so, some
> sanity will prevail over re-using code points and similar fatal issues.
> as you suggest, perhaps a good practice would be never to delete a
> profile - at worst, deprecate it, but even that would be exceptional.
> I'd support forbidding the "delete" operation.

i think these would be good guidelines to follow, but they should be 
codified, so that developers can learn about them and use them in their 
code.

http://tools.ietf.org/html/rfc5226 is excellent reading for all of the 
issues that should go into defining and running a registry. i am not 
saying it has to be done exactly that way, but a lot of experience has 
resulted in these issues being identified as the ones that should be 
well-defined for a registry.

> for updates (version management) we should recommend the assignments be
> stable. and the WG can do that for its own profiles. but I'm not sure
> the WG can dictate how 3rd parties manage the evolution of their
> controlling specs except via recommendations.

you can require updates to not break semantics, and you can refuse to 
accept updates that do, because those would violate assumption that 
developers and thus code depends on.

> can you propose specific edits?

i'd be glad to help, but first i want to better understand how you see 
the space evolving.

generally speaking, i find the idea of having "the registry" as a table 
in the "registry document" a rather odd construct. i'd much rather see 
the registry being defined, and then being available in some format 
that's easy to use, such as CSV, XML, or JSON.

seeing that this is a recurring issue in recent w3c specs, maybe i will 
start playing with some ideas of how to make this a bit more structured 
and machine-friendly, and then propose an alternative way of doing this.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/tt-profile-registry/issues/17#issuecomment-218260667

## 

erik wilde | mailto:erik.wilde@dret.net |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by mikedo** [comment]
The main purpose of the registry part of this document is to enable defined @codecs values for DASH, not encourage lots of profiles. Unlike many registries, having lots of entries (lots of profiles) is undesirable. So, I don't want to over-engineer this. Maybe a SHOULD citation to RFC5226 would suffice as a WG operational reminder (in addition to removing "delete")?

**Comment by nigelmegitt** [comment]
Nevertheless, it's an excellent point that @dret has raised. I would support adding some words that say that we will never reuse a short code but may deprecate them on request. New versions of specs or profiles must be given new short codes. Are there any circumstances where this wouldn't be true? I'm thinking of superset/subset type rules.

**Comment by dret** [comment]
On 2016-05-11 07:32, Nigel Megitt wrote:

> Nevertheless, it's an excellent point that @dret
> https://github.com/dret has raised. I would support adding some words
> that say that we will never reuse a short code but may deprecate them on
> request. New versions of specs or profiles must be given new short
> codes. Are there any circumstances where this wouldn't be true? I'm
> thinking of superset/subset type rules.

i think this makes a lot of sense. from a specification point of view, 
you'd probably want to add a column to the registry that's something 
like "status: active/deprecated", so that registry updates could 
specifically update that value. also, you might want to say that once 
deprecated, entries never go back to being active.

**Comment by dret** [comment]
On 2016-05-11 07:24, Michael A Dolan wrote:

> The main purpose of the registry part of this document is to enable
> defined @codecs https://github.com/codecs values for DASH, not
> encourage lots of profiles. Unlike many registries, having lots of
> entries (lots of profiles) is undesirable. So, I don't want to
> over-engineer this. Maybe a SHOULD citation to RFC5226 would suffice as
> a WG operational reminder (in addition to removing "delete")?

fair enough, and point taken on "not over-engineering". it's unfortunate 
that w3c provides no support for establishing profiles, it would make 
things much easier.

i don't think there's any need to reference RFC 5226, i simply wanted to 
point to a standards body that has a lot of experience in using 
registries, mostly as an inspiration.

https://tools.ietf.org/html/draft-wilde-registries is intended for spec 
writers considering establishing and managing a registry. it is meant as 
a list of issues to think about. maybe it's helpful. if not, any 
feedback would be greatly appreciated, ideally in the form of comments 
or issues at https://github.com/dret/I-D/tree/master/registries

**Comment by nigelmegitt** [comment]
TTWG Meeting 2016-05-19: Group is in general agreement that short codes should not be reused, however the responsibility for deciding this on a case by case basis belongs with the group. We support the idea of adding text even if no stronger than guidance for the group to follow in future.

**Comment by mikedo** [comment]
Fixed in  9f47c1e
