### ISSUE TITLE
spurious # in URLs table 4.1

### ISSUE THREAD

**Issue by frans-ebu** [w3c/tt-profile-registry#29]
@nigelmegitt I see two '#' at the end of the URLs pointing to the requester contact of etx1, ext2, etd1
I'd suggest the '#' character should be removed.

https://tech.ebu.ch/ebu-tt# -> https://tech.ebu.ch/ebu-tt

**Comment by nigelmegitt** [comment]
When I click on that link it takes me to https://tech.ebu.ch/subtitling - why do we not use that URL directly?

**Comment by frans-ebu** [comment]
Agreed, even better.

**Comment by tmichel07** [comment]
I have made a Pull request with these changes

**Comment by mikedo** [comment]
Pull request merged.
