### ISSUE TITLE
Consider how to handle Content Profiles vs Processor Profiles

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/tt-profile-registry#38]
This arises from a comment by @mikedo that the WG couldn't locate during today's WG meeting, but it seems important.

**Comment by skynavga** [comment]
Text referring (explicitly or implicitly) to content profiles has already been removed by recent PRs, except in the note in §1 which states that content profiles are out of scope for this document. As such, I believe this issue is non-actionable, and am therefore closing as moot.
