### ISSUE TITLE
Add EBU-TT profiles

### ISSUE THREAD

**Issue by frans-ebu** [w3c/tt-profile-registry#42]
EBU requests the addition of the following profile identifiers and
designators:

Profile Identifier: `etx3`
Profile Designator: `urn:ebu:tt:exchange:2017-05`
Public Specification: [EBU-TT-1-2] pointing to
`https://tech.ebu.ch/docs/tech/tech3350v1_2.pdf`
XPATH to element or attribute (2 options):
`/tt:tt/tt:head/tt:metadata/ebuttm:conformsToStandard`
`/tt:tt/tt:head/tt:metadata/ebuttm:documentMetadata/ebuttm:conformsToStandard` [deprecated]

Value of element or attribute: `urn:ebu:tt:exchange:2017-05`

Profile Identifier: `etd2`
Profile Designator: `urn:ebu:tt:distribution:2018-04`
Public Specification: [EBU-TT-D-1-0-1] pointing to
`https://tech.ebu.ch/docs/tech/tech3380v1_0_1.pdf`
XPATH to element or attribute (2 options):
`/tt:tt/tt:head/tt:metadata/ebuttm:conformsToStandard`
`/tt:tt/tt:head/tt:metadata/ebuttm:documentMetadata/ebuttm:conformsToStandard` [deprecated]
Value of element or attribute: `urn:ebu:tt:distribution:2018-04`

Profile Identifier: `etl1`
Profile Designator: `urn:ebu:tt:live:2017-05`
Public Specification: [EBU-TT-Live] pointing to
`https://tech.ebu.ch/docs/tech/tech3370v1_0.pdf`
XPATH to element or attribute (2 options):
`/tt:tt/tt:head/tt:metadata/ebuttm:conformsToStandard`
`/tt:tt/tt:head/tt:metadata/ebuttm:documentMetadata/ebuttm:conformsToStandard` [deprecated]
Value of element or attribute: `urn:ebu:tt:live:2017-05`

**Comment by nigelmegitt** [comment]
Discussed in TTWG meeting just now, no objection raised.
