### ISSUE TITLE
Add informative mention of EBU-TT Metadata

### ISSUE THREAD

**Issue by frans-ebu** [w3c/tt-profile-registry#43]
EBU requests the addition of an appendix in which related specifications can be listed.

Initially EBU proposes to include an informative reference to [EBU-TT-M] pointing to `https://tech.ebu.ch/docs/tech/tech3390.pdf` with the explanation that the specification defines a vocabulary that is available for use in EBU-TT and other TTML document instances for the purpose of describing metadata primarily relating to the contribution, exchange and archive of subtitle and caption documents.

**Comment by cconcolato** [comment]
Could we just add a note to section 4.2, e.g. after the table indicating that elements using the `ebuttm` prefix are defined in [EBU-TT-M] and have an informative/normative reference to that document as usual?

**Comment by frans-ebu** [comment]
Tnx @cconcolato, sounds good to me.

**Comment by skynavga** [comment]
Addressed in https://github.com/w3c/tt-profile-registry/commit/49d65bd3f7a05185779817dd061bdf76963e24f6.
