### ISSUE TITLE
Registry is not used to exchange profiles

### ISSUE THREAD

**Issue by cconcolato** [w3c/tt-profile-registry#46]
The following sentence is confusing:
> This registry can be used by other entities to exchange processor profiles in a compact way. 

I suggest deleting it or rephrasing as:
> The identifiers defined in this registry can be used by entities to exchange processor profiles in a compact way.

**Comment by nigelmegitt** [comment]
Seems like a good change to me.

**Comment by skynavga** [comment]
The cited text, and, in particular, references to the exchange of profiles, no longer exists due to recent PRs. Closing this issue as moot.
