### ISSUE TITLE
add media type registration section

### ISSUE THREAD

**Issue by mikedo** [w3c/tt-profile-registry#5]
Create a new section that provides the required IANA media type registration information adding a new parameter "codecs" using the defined short name syntax and considering:
http://ietf.org/rfc/rfc6381.txt
https://www.w3.org/TR/2013/REC-ttml1-20130924/#media-types-registration
http://www.iana.org/assignments/media-types/application/ttml+xml
https://www.w3.org/2002/06/registering-mediatype2014.html
http://www.iana.org/form/media-types

**Comment by plehegar** [comment]
can we close this?
