### ISSUE TITLE
Update references and fix/clarify various problems with language.

### ISSUE THREAD

**Issue by skynavga** [w3c/tt-profile-registry#52]
- [x] Fix respec warning for normative TTML2 reference in non-normative section.
- [x] Replace ambiguous references to TTML1 with stable references to specific editions.
- [x] Improve reference labeling consistency for all TTML, IMSC references.
- [x] Use local bibliographic entries for all references to allow greater control of entry content.
- [x] Improve specificity and applicability of profile identification in abstract.
- [x] Miscellaneous editorial improvements to language.
- [x] Add co-editor.

**Comment by nigelmegitt** [comment]
Please describe what the editorial issues are - this issue is currently not well formed.

[Update: thanks for adding that into the main issue @skynavga ]
