### ISSUE TITLE
Remove §4.2, Path and value.

### ISSUE THREAD

**Issue by skynavga** [w3c/tt-profile-registry#53]

**Comment by nigelmegitt** [comment]
See discussion in https://www.w3.org/2018/10/22-tt-minutes.html#item03

**Comment by nigelmegitt** [comment]
The discussion linked suggests there was consensus for making §4.2 an informative appendix. In its current form #64 simply removes the section altogether; I do not think we have consensus for that approach at this time.

**Comment by skynavga** [comment]
Actually, from what I heard then, and more recently, both @palemieux and myself preferred removal, for which I see two main motivations: (1) the material is potentially misleading since it suggest an algorithm for determining whether a document is associated with a profile that is not defined by TTML itself; and, (2) it presents an ongoing maintenance problem. The consensus I have heard is to make this document brief in order to serve its two documented purposes, which do not include the material in 4.2 and its suggested association algorithm.
