### ISSUE TITLE
Link to EBU Tech 3350 version 1.2 incorrect

### ISSUE THREAD

**Issue by andreastai** [w3c/tt-profile-registry#60]
The link to EBU-TT Tech 3350 version 1.2 should be https://tech.ebu.ch/docs/tech/tech3350v1_2.pdf. In the Normative reference section it is instead https://tech.ebu.ch/docs/tech/tech3350v1-2.pdf. In the correct URL the version is delimited by `_` not `-`.

**Comment by nigelmegitt** [comment]
Thanks @tairt this is actually a problem with the entry I added to Specref so I'll fix it there and post back here when that's done.

**Comment by nigelmegitt** [comment]
I've opened tobie/specref#500 to resolve this.

**Comment by nigelmegitt** [comment]
The reference is now fixed, thanks for filing this @tairt !

If I might be permitted a short polemic, this fix was made with no code changes to this repository, and the fix benefits anyone who uses Specref to get their document references. This is more powerful and useful than defining the references locally in the document only, where any fixes will only be applied locally. This is an argument in favour of using Specref for reference details.

**Comment by andreastai** [comment]
@nigelmegitt Perfect! Thanks!
