### ISSUE TITLE
Elaborate + and | operators further.

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/tt-profile-registry#62]
The `codecs` parameter is defined to take a syntax that allows for optional (`|`) or combined ('+') processor profiles, and references https://www.w3.org/TR/ttml2/#profile-attribute-processorProfileCombination however that section does not define those operators further.

In particular we need to explain if the `+` operator implies that it is acceptable or even required to perform processor profile combination as per TTML2 prior to assessing processor acceptability, in which case:
* the order of operands matters (i.e. perhaps surprisingly the operator is not commutative)
* which value of the `combine` attribute applies - the first/second/strictest?

As currently written it appears that processor profile combination is orthogonal, since the text just says that `+` means that both processor profiles apply. From that perspective, the pointer to processor profile combination is perhaps misleading.

**Comment by cconcolato** [comment]
> we need to explain if the `+` operator implies that it is acceptable or even required to perform processor profile combination as per TTML2 prior to assessing processor acceptability

The operators in the `codecs` parameter are meant to be used before the document is downloaded/opened.  I

I think the reference to processor profile combination is not clear but the intent was to provide a normative definition of how the operators behave. I think `+` is meant to behave like `mostRestrictive` and `|` like `leastRestrictive`. 

Note also the use of 'must' in an "The example:" paragraph in a non-normative section...

**Comment by skynavga** [comment]
Actually, the intent of ``"|"`` and ``"+"`` was to serve as a shorthand for the ``any(...)`` and ``all(...)`` syntax defined for use with the ``ttp:processorProfiles`` attribute as defined by https://www.w3.org/TR/2018/REC-ttml2-20181108/#profile-attribute-processorProfiles. However, that section of TTML2 does not formally map that logic onto the TTML profile combination method logic, which is something we should consider adding in TTML2 2e.

Notwithstanding the above, the codecs parameter goes even further by permitting  a combination of ``any(...)`` and ``all(...)`` that is not directly supported in TTML2. We should probably either impose (new) restrictions on the ``codecs`` parameter or extend TTML2 to support such combinations in the ``ttp:processorProfiles`` attribute.
