### ISSUE TITLE
The codecs parameter and media type registration.

### ISSUE THREAD

**Issue by mikedo** [w3c/tt-profile-registry#63]
A reminder that any changes to the media type information in section 2 requires IANA and IETF expert review through the normal process between W3C and IANA. This should be done before publication.

The codecs parameter was created to be used in ISO BMFF and DASH MPD. Thus, it needs to conform to RFC 6381 syntax.  That is, the entire codecs parameter string must conform to RFC 6381 (not just the profile code).  The RFC 6381 citation should be moved to the codecs parameter text.

If we want to constrain the charset of the profile code, then we can point to 4CC in ISO/IEC 14496-12. Note that a recent update to that constrained 4CC to a subset of ASCII (0x20-0x7E).

**Comment by skynavga** [comment]
@mikedo a few questions/comments

1. Since the W3C is the designated "change controller", then is it correct to say that an IETF expert review is strictly a formality, and not required by process?

2. As specified, the registration does not refer to RFC 6381 and does not define a formal syntax (or charset) but implies that the syntax is effectively

```
codecs-parameter-value :
  short-identifier [ ( "|" | "+" ) short-identifier ]*

short-identifier :
  4*<any TOKEN character except "|" and "+">
```

I can see that it may desirable to make this syntax more concrete, and perhaps even more restricted, e.g., allowing only ASCII alpha and digit characters in a short-identifier.

Do you think we need to do this in the next edition of the published NOTE or in a subsequent edition (giving us more time to resolve these changes separately from pushing out the door our current changes)?

**Comment by mikedo** [comment]
I'm confident in the review process for changes.  Philippe manages it I believe (he did last time).

RFC 6381 is cited here:  https://w3c.github.io/tt-profile-registry/#Registration_Entry_Requirements_and_Update_Process  It needs to be in the codecs parameter paragraph instead. It does not help to have it for the individual codes.

We need to ensure the syntax is valid now hopefully before anyone uses the more complex operator syntax. I have a 6381 regex if someone will prepare a few complex examples, If they pass, then we can defer on perfecting the syntax. The 6381 citation needs to be fixed though so that we're covered until there is more concrete syntax,

**Comment by skynavga** [comment]
Here are some possible values for the ``codecs`` parameter

```
im2t
im2t|im2i
im2t+im2i
tt2p|tt1p|im1t|im1i
tt2p+tt2t|tt1p+tt1t|im1t|im1i
```

**Comment by mikedo** [comment]
I have a draft work in process XML regex for DASH MPD @codecs (RFC 6381).  The above examples all validate.  That’s good and gives some level of confidence that we can defer a more concrete syntax for the profile code itself.

**Comment by cconcolato** [comment]
I agree with @mikedo we should formally define the use of + and | as part of the MIME type definition, even if it means a new review by IANA. Why is that a problem?

**Comment by skynavga** [comment]
@cconcolato There was a pretty clear consensus in the last telecon (which Mike attended) that we didn't want (or need) to alter the MIME type definition in a manner that would require IANA review. We can check again at this week's telecon whether that consensus has changed.

**Comment by mikedo** [comment]
If everyone still wants to support this combinatorial syntax, then we still need to define it formally such as proposed in point 2 from 28-Feb-19.

Further, I believe that it requires a supporting companion syntax in TTML itself using the @xxxprofiles strings which is currently only "+".  The registry is just that – a register of profile shorthand codes.  If the syntax is not supported in TTML @xxxprofiles, then what supports doing it in the registry?

So *if* we are serious about this syntax in the registry, it should be supported in TTML itself. The shorthand here can mimic that.  And someone needs to define the ABNF/regex for what they had in mind, and not just provide a few examples.

Else we should remove all but a simple "+" and define the semantics to be what's in TTML @xxxprofiles.

**Comment by nigelmegitt** [comment]
@mikedo sorry, we closed this issue because we resolved it all except for the combinatorial syntax definition, and opened #71 specifically to discuss that remaining part of the issue. Would you mind adding https://github.com/w3c/tt-profile-registry/issues/63#issuecomment-650248688 to #71 instead?
