### ISSUE TITLE
Add IMSC 1.2 Text and Image Profiles, change Editors

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/tt-profile-registry#74]
Agreed in w3c/ttwg#123 to:

* [x] Add im3t pointing to IMSC 1.2 Text Profile
* [x] Add IMSC 1.2 spec-link to im2i's entry, in addition to IMSC 1.1

**Comment by nigelmegitt** [comment]
As discussed in w3c/ttwg#123, also add me as Editor.

**Comment by nigelmegitt** [comment]
@skynavga has asked to step down as an Editor, so I'll add him to the previous editor's list as part of this ticket.

**Comment by cconcolato** [comment]
Do we need to keep mentioning editors for such a small document? We could say `Authors: TTWG`

**Comment by nigelmegitt** [comment]
> Do we need to keep mentioning editors for such a small document? We could say `Authors: TTWG`

We've had Editors on this document until now, so I don't want to change the precedent. It's also very easy to manage using Respec. I'd consider a different approach for a new document, if the tools support it.
